---
output: 
html_document:
code_folding: hide
pagetitle: Programming
---
<style type="text/css">
.main-container {
  max-width: 1800px;
  margin-left: auto;
  margin-right: auto;
}
</style>

<style>
div.blue { background-color:#63a898; border-radius: 5px; padding: 20px;}
</style>
<div class = "blue">



<style>
div.blue { background-color:#63a898; border-radius: 0px; padding: 20px;}
</style>
<div class = "blue">


## [HOME](http://AR-Polyhedron.github.io/) | [ABOUT ME](http://AR-Polyhedron.github.io/About_Me/) | [CV](http://AR-Polyhedron.github.io/CV/) | [PROGRAMMING](http://AR-Polyhedron.github.io/Programming/) | [RESEARCH](http://AR-Polyhedron.github.io/Research/) 

### [Data_Course](https://github.com/AR-Polyhedron/Data_Course_RAAB) | [Exam 3](http://AR-Polyhedron.github.io/Exam_3/) | [Final](http://AR-Polyhedron.github.io/Final_Project/) 
 

### Welcome to the begining of my Programming work.You should notice some additional links above now. The first belongs to the culminated work I did for the class that tought me R. The second and third links are to the last projects performed for the class and are made in RMarkdown, thus viewable on the site. Though fair warning to these, they are rough at parts. Especially the Final Project. I have not had the oppturnity to follow-up what I learned with new projects and refine my skills. However I hope to do so and to fill this section with much more. Though I still feel these demonstrate my skill and knowledge I have with the language so I offer them to be viewed. 

<br><br><br><br><br><br><br><br><br>
<br><br><br><br><br><br><br><br><br>
<br><br><br><br><br><br><br><br><br>