---
output: 
html_document:
code_folding: hide
pagetitle: CV
---
<style type="text/css">
.main-container {
  max-width: 1800px;
  margin-left: auto;
  margin-right: auto;
}
</style>

<style>
div.blue { background-color:#63a898; border-radius: 5px; padding: 20px;}
</style>
<div class = "blue">



<style>
div.blue { background-color:#63a898; border-radius: 0px; padding: 20px;}
</style>
<div class = "blue">


## [HOME](http://AR-Polyhedron.github.io/) | [ABOUT ME](http://AR-Polyhedron.github.io/About_Me/) | [CV](http://AR-Polyhedron.github.io/CV/) | [PROGRAMMING](http://AR-Polyhedron.github.io/Programming/) | [RESEARCH](http://AR-Polyhedron.github.io/Research/) 

# Alexander Raab

### **Student**

385-250-4434 | alexraab1@gmail.com |

<br>

### **Summary**
During my schooling I worked a number of customer service job. Through this work history I developed a strong sense of working with a team, and excelling in a stressful environment. My skills are best exemplified within a laboratory setting. During my education I interned primarily under Dr. Lauren Brooks, and secondarily under Dr. Geoffry Zahn, as a research student. During this time, I was twice awarded funding to pursue research. In which I conducted an ecological survey of the local fungi of Utah and to identify a Broad Host Range plasmid. Both included extensive work in Utah Valley University’s Microbiology lab, sterile procedure of a BSL-2 lab, culturing, electrophoresis, and real-time qPCR. I have prepared dozens of specimens to kept at Bean Life Science Museum Reptile and Amphibian research collection. I also have over six months experience with the programming language R, my work with it can be seen above in Programming.
<br>

### **Experience**
* Student Support Position, AFHS Biology & Chemistry Department, American Fork, Utah 2012-2013

* **Buser**, Outback Steak House, Blooming Brands, Orem, Utah 2014-2015

* **Outbound Phone Operator**, BRG Research Services, Orem, Utah 2016-2016

* **Day-care Worker**, Self-employed, Pleasant Grove, Utah 2017-2017

* **Customer Email Team**, Vetora llc, Orem, Utah 2019-2020

* **Student Researcher**, Utah Valley University, Orem, Utah 2018-2020
<br>

### **Education**
* **Associate's of Science**, Utah Valley University, Orem, Utah 2013-2018

* **Bachelor’s**, Utah Valley University, Orem, Utah 2013-Anticipated 08/19/2020

<br>

### **Community Service**

**Secretary**, Utah Valley University, Pre-Veterinarian Medicine Club, Orem, Utah 2018-2019.I kept the minutes of meetings, participated in numerous club events such as fund raisers and service projects, and managed communications for the organization. 

<br>

**Treasurer**, American Fork FFA, American Fork, Utah 2013-2014
I kept track of the organization’s budget, attended events across the state of Utah, kept track of student membership, and was crucial to the chapter winning an Award in record keeping at the FFA 2014 Convention.
<br>

</div>



